name: cookbook
description: "Livro de Receitas"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: 
  mask_text_input_formatter: 
  date_format: 
  multiselect_dropdown_flutter: 
  multi_select_flutter: 
  intl: 
  file_picker: 
  path_provider: 
  image_picker: ^1.0.4
  flutter_image_compress: ^2.1.0
  sqflite: ^2.3.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  entry_point: lib/view/main.dart

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
